/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Horario.Horario;
import javax.swing.table.DefaultTableModel;
import static views.intADM.tabela;
import views.teste.Horas;
import views.teste.Minutos;
import views.teste.Segundos;

/**
 *
 * @author César
 */
public class intuUsuario extends javax.swing.JFrame {

    public static void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Horas horas;
    Minutos minutos;
    Segundos segundos;

    Thread tHor, tMin, tSeg;

    //
    Hora2 hora2;
    Minutos2 minutos2;
    Segundos2 segundo2;

    Thread tHor2, tMin2, tSeg2;

    //
    int clic1;
    int clic2;

    /**
     * Creates new form intuUsuario
     */
    public intuUsuario() {
        initComponents();
        //Horas
        horas = new Horas();
        tHor = new Thread(horas);
        //Minutos
        minutos = new Minutos();
        tMin = new Thread(minutos);
        //Segundos
        segundos = new Segundos();
        tSeg = new Thread(segundos);

        //Horas 2
        hora2 = new Hora2();
        tHor2 = new Thread(hora2);
        //Minutos2
        minutos2 = new Minutos2();
        tMin2 = new Thread(minutos2);
        //Segundos2
        segundo2 = new Segundos2();
        tSeg2 = new Thread(segundo2);

        //
        clic1 = 0;
        //
        clic2 = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        txtHor1 = new javax.swing.JTextField();
        txtMin1 = new javax.swing.JTextField();
        txtHor2 = new javax.swing.JTextField();
        txtMin2 = new javax.swing.JTextField();
        txtSeg1 = new javax.swing.JTextField();
        txtSeg2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 47, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 74, 221, 29));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 134, 221, 32));

        jLabel3.setText("Identificador Único :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 110, -1, -1));

        jButton3.setText("Início");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 79, -1));

        jButton4.setText("Termino");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 91, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Início", "Termino", "Data de Acesso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 25, 430, 190));

        jLabel4.setText("Cargo :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, 30));

        txtHor1.setText("0");
        jPanel1.add(txtHor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 30, 30));

        txtMin1.setText("0");
        txtMin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMin1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 30, 30));

        txtHor2.setText("0");
        jPanel1.add(txtHor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 30, 30));

        txtMin2.setText("0");
        jPanel1.add(txtMin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 30, 30));

        txtSeg1.setText("0");
        jPanel1.add(txtSeg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 30, 30));

        txtSeg2.setText("0");
        jPanel1.add(txtSeg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 30, 30));

        jButton1.setText("Início");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 80, -1));

        jButton2.setText("Termino");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 270, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sistem Ponto (2).png"))); // NOI18N
        jLabel2.setText("img");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Menu");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Altera a senha ");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Suporte");
        jMenu1.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Sair");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMin1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (!tHor.isAlive()) {
            tHor.start();
        }
        if (!tMin.isAlive()) {
            tMin.start();
        }
        if (!tSeg.isAlive()) {
            tSeg.start();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!tHor2.isAlive()) {
            tHor2.start();
        }
        if (!tMin2.isAlive()) {
            tMin2.start();
        }
        if (!tSeg2.isAlive()) {
            tSeg2.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (clic1 == 0) {
            Object[] col;
            col = new Object[3];
            col[0] = "Volta";
            col[1] = "Hora";
            col[2] = "Duração Total";
            Object[][] lin;
            lin = new Object[1][3];
            lin[0][0] = "1";
            lin[0][1] = txtHor1.getText() + ":" + txtMin1.getText() + ":" + txtSeg1.getText();
            lin[0][2] = txtHor1.getText() + ":" + txtMin1.getText() + ":" + txtSeg1.getText();
            DefaultTableModel tm;
            tm = new DefaultTableModel(lin, col);
            jTable1.setModel(tm);
            clic1 = 1;

        } else {
            //JOptionPane.showMessageDialog(this, "clicou");
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            Object[] lin;
            lin = new Object[3];
            lin[0] = tm.getRowCount() + 1;
            //lin[1]=txtMin.getText()+":"+txtSeg.getText()+":"+txtMil.getText();
            lin[2] = txtHor1.getText() + ":" + txtMin1.getText() + ":" + txtSeg1.getText();
            System.out.println("Somar");
            int min = Integer.parseInt(txtHor1.getText());
            int seg = Integer.parseInt(txtMin1.getText());
            int mil = Integer.parseInt(txtSeg1.getText());

            System.out.println(min + " " + seg + " " + mil);
            Object tudo = jTable1.getModel().getValueAt(tm.getRowCount() - 1, 2);
            System.out.println(tudo);
            String minSegMil = (String) tudo;
            String[] tem = minSegMil.split(":");
            int min2 = Integer.parseInt(tem[0]);
            int seg2 = Integer.parseInt(tem[1]);
            int mil2 = Integer.parseInt(tem[2]);

            int minResp;
            int segResp;
            int milResp;
            minResp = min - min2;
            segResp = seg - seg2;
            milResp = mil - mil2;
            System.out.println("..." + segResp);

            lin[1] = minResp + ":" + segResp + ":" + Math.abs(milResp);
            tm.addRow(lin);
        }
        //
        try {
            tHor.stop();
            tMin.stop();
            tSeg.stop();
            txtHor1.setText("0");
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (clic2 == 1) {
            Object[] col;
            col = new Object[3];
            col[1] = "Primeiro tudono";
            col[2] = "Hora";
            col[3] = "Duração Total";
            Object[][] lin;
            lin = new Object[1][3];
            lin[0][0] = "1";
            lin[0][1] = txtHor2.getText() + ":" + txtMin2.getText() + ":" + txtSeg2.getText();
            lin[0][2] = txtHor2.getText() + ":" + txtMin2.getText() + ":" + txtSeg2.getText();
            DefaultTableModel tm;
            tm = new DefaultTableModel(lin, col);
            jTable1.setModel(tm);
            clic2 = 1;

        } else {
            //JOptionPane.showMessageDialog(this, "clicou");
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            Object[] lin;
            lin = new Object[3];
            lin[0] = tm.getRowCount() + 1;
            //lin[1]=txtMin.getText()+":"+txtSeg.getText()+":"+txtMil.getText();
            lin[2] = txtHor2.getText() + ":" + txtMin2.getText() + ":" + txtSeg2.getText();
            System.out.println("Somar");
            int hor = Integer.parseInt(txtHor2.getText());
            int min = Integer.parseInt(txtMin2.getText());
            int seg = Integer.parseInt(txtSeg1.getText());

            System.out.println(hor + " " + min + " " + seg);
            Object tudo = jTable1.getModel().getValueAt(tm.getRowCount() - 1, 2);
            System.out.println(tudo);
            String minSegMil = (String) tudo;
            String[] tem = minSegMil.split(":");
            int ho2 = Integer.parseInt(tem[0]);
            int min2 = Integer.parseInt(tem[1]);
            int seg2 = Integer.parseInt(tem[2]);

            int hoResp;
            int minResp;
            int segResp;
            hoResp = ho2 - ho2;
            minResp = min - min2;
            segResp = seg - seg2;
            System.out.println("..." + segResp);

            lin[1] = minResp + ":" + minResp + ":" + Math.abs(segResp);
            tm.addRow(lin);
        }
        //
        try {
            tHor2.stop();
            tMin2.stop();
            tSeg2.stop();
            txtHor2.setText("0");
        } catch (Exception ex) {

        }
        //
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
         new alteraUSU().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intuUsuario().setVisible(true);

            }
        });
    }

    /*public static void preenchertabela () {
     DefaultTableModel model = (DefaultTableModel) tabela.getModel();
     model.setNumRows(0);
        
     Object coluna [] = new Object[4];
     Horario horario = new Horario(null, null, null);
        
        
        
     }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField txtHor1;
    public static javax.swing.JTextField txtHor2;
    public static javax.swing.JTextField txtMin1;
    public static javax.swing.JTextField txtMin2;
    public static javax.swing.JTextField txtSeg1;
    public static javax.swing.JTextField txtSeg2;
    // End of variables declaration//GEN-END:variables
}
